# Tfidf from scratch

In [1]:
import numpy as np
import platform
import matplotlib as mpl                   #importing libraries
import matplotlib.pylab as plt
print(platform.python_version())
print(np.__version__)
print(mpl.__version__)
print(plt.__version__)

3.8.3
1.18.5
3.2.2
1.18.5

In [2]:
import pandas as pd
import math
import sklearn as sk

In [3]:
dataset = ["I enjoy reading about Machine Learning and I am doing masters in Artificial Intelligence.",
           "I enjoy a lot in my university campus but now stuck in my home because of Covid lockdown.",
           "Our university library has lots of books on machine learning."]

In [4]:
sentence_1 = dataset[0].split(" ")
sentence_2 = dataset[1].split(" ")
sentence_3 = dataset[2].split(" ")
word_list = set(set(sentence_1).union(set(sentence_2))).union(set(sentence_3))
word_list

{'Artificial',
 'Covid',
 'I',
 'Intelligence.',
 'Learning',
 'Machine',
 'Our',
 'a',
 'about',
 'am',
 'and',
 'because',
 'books',
 'but',
 'campus',
 'doing',
 'enjoy',
 'has',
 'home',
 'in',
 'learning.',
 'library',
 'lockdown.',
 'lot',
 'lots',
 'machine',
 'masters',
 'my',
 'now',
 'of',
 'on',
 'reading',
 'stuck',
 'university'}

In [5]:
def word_dict(): #creates word dictionary with pre filled values as zero
    word_dict = {}
    word_dict = dict.fromkeys(word_list,0)
    return word_dict

In [6]:
word_dictionary_1 = dict.fromkeys(word_list,0)
word_dictionary_2 = dict.fromkeys(word_list,0)
word_dictionary_3 = dict.fromkeys(word_list,0)
print("\n 1: ",word_dictionary_1,"\n 2: ",word_dictionary_2,"\n 3: ",word_dictionary_3)

 1:  {'my': 0, 'of': 0, 'has': 0, 'a': 0, 'on': 0, 'machine': 0, 'but': 0, 'lot': 0, 'now': 0, 'Learning': 0, 'campus': 0, 'library': 0, 'Our': 0, 'and': 0, 'about': 0, 'in': 0, 'masters': 0, 'am': 0, 'Intelligence.': 0, 'I': 0, 'learning.': 0, 'Machine': 0, 'reading': 0, 'doing': 0, 'enjoy': 0, 'Covid': 0, 'stuck': 0, 'lockdown.': 0, 'lots': 0, 'books': 0, 'home': 0, 'because': 0, 'university': 0, 'Artificial': 0}
 2:  {'my': 0, 'of': 0, 'has': 0, 'a': 0, 'on': 0, 'machine': 0, 'but': 0, 'lot': 0, 'now': 0, 'Learning': 0, 'campus': 0, 'library': 0, 'Our': 0, 'and': 0, 'about': 0, 'in': 0, 'masters': 0, 'am': 0, 'Intelligence.': 0, 'I': 0, 'learning.': 0, 'Machine': 0, 'reading': 0, 'doing': 0, 'enjoy': 0, 'Covid': 0, 'stuck': 0, 'lockdown.': 0, 'lots': 0, 'books': 0, 'home': 0, 'because': 0, 'university': 0, 'Artificial': 0}
 3:  {'my': 0, 'of': 0, 'has': 0, 'a': 0, 'on': 0, 'machine': 0, 'but': 0, 'lot': 0, 'now': 0, 'Learning': 0, 'campus': 0, 'library': 0, 'Our': 0, 'and': 0, 'about': 0, 'in': 0, 'masters': 0, 'am': 0, 'Intelligence.': 0, 'I': 0, 'learning.': 0, 'Machine': 0, 'reading': 0, 'doing': 0, 'enjoy': 0, 'Covid': 0, 'stuck': 0, 'lockdown.': 0, 'lots': 0, 'books': 0, 'home': 0, 'because': 0, 'university': 0, 'Artificial': 0}

In [7]:
def count(word_dictionary, sentence):
    for word in sentence:
        word_dictionary[word]+=1

In [8]:
count(word_dictionary_1, sentence_1)
word_dictionary_1

{'my': 0,
 'of': 0,
 'has': 0,
 'a': 0,
 'on': 0,
 'machine': 0,
 'but': 0,
 'lot': 0,
 'now': 0,
 'Learning': 1,
 'campus': 0,
 'library': 0,
 'Our': 0,
 'and': 1,
 'about': 1,
 'in': 1,
 'masters': 1,
 'am': 1,
 'Intelligence.': 1,
 'I': 2,
 'learning.': 0,
 'Machine': 1,
 'reading': 1,
 'doing': 1,
 'enjoy': 1,
 'Covid': 0,
 'stuck': 0,
 'lockdown.': 0,
 'lots': 0,
 'books': 0,
 'home': 0,
 'because': 0,
 'university': 0,
 'Artificial': 1}

In [9]:
count(word_dictionary_2, sentence_2)
word_dictionary_2

{'my': 2,
 'of': 1,
 'has': 0,
 'a': 1,
 'on': 0,
 'machine': 0,
 'but': 1,
 'lot': 1,
 'now': 1,
 'Learning': 0,
 'campus': 1,
 'library': 0,
 'Our': 0,
 'and': 0,
 'about': 0,
 'in': 2,
 'masters': 0,
 'am': 0,
 'Intelligence.': 0,
 'I': 1,
 'learning.': 0,
 'Machine': 0,
 'reading': 0,
 'doing': 0,
 'enjoy': 1,
 'Covid': 1,
 'stuck': 1,
 'lockdown.': 1,
 'lots': 0,
 'books': 0,
 'home': 1,
 'because': 1,
 'university': 1,
 'Artificial': 0}

In [10]:
count(word_dictionary_3, sentence_3)
word_dictionary_3

{'my': 0,
 'of': 1,
 'has': 1,
 'a': 0,
 'on': 1,
 'machine': 1,
 'but': 0,
 'lot': 0,
 'now': 0,
 'Learning': 0,
 'campus': 0,
 'library': 1,
 'Our': 1,
 'and': 0,
 'about': 0,
 'in': 0,
 'masters': 0,
 'am': 0,
 'Intelligence.': 0,
 'I': 0,
 'learning.': 1,
 'Machine': 0,
 'reading': 0,
 'doing': 0,
 'enjoy': 0,
 'Covid': 0,
 'stuck': 0,
 'lockdown.': 0,
 'lots': 1,
 'books': 1,
 'home': 0,
 'because': 0,
 'university': 1,
 'Artificial': 0}

In [12]:
df=pd.DataFrame([word_dictionary_1,word_dictionary_2,word_dictionary_3])
df.T

               0  1  2
my             0  2  0
of             0  1  1
has            0  0  1
a              0  1  0
on             0  0  1
machine        0  0  1
but            0  1  0
lot            0  1  0
now            0  1  0
Learning       1  0  0
campus         0  1  0
library        0  0  1
Our            0  0  1
and            1  0  0
about          1  0  0
in             1  2  0
masters        1  0  0
am             1  0  0
Intelligence.  1  0  0
I              2  1  0
learning.      0  0  1
Machine        1  0  0
reading        1  0  0
doing          1  0  0
enjoy          1  1  0
Covid          0  1  0
stuck          0  1  0
lockdown.      0  1  0
lots           0  0  1
books          0  0  1
home           0  1  0
because        0  1  0
university     0  1  1
Artificial     1  0  0

#### TF computation

In [13]:
def TF(word_dictionary, length):
    tf_dict = {}

    for word, count in word_dictionary.items():
        tf_dict[word] = count/length
    return tf_dict

In [14]:
tf_1 = TF(word_dictionary_1,float(len(sentence_1)))
tf_1

{'my': 0.0,
 'of': 0.0,
 'has': 0.0,
 'a': 0.0,
 'on': 0.0,
 'machine': 0.0,
 'but': 0.0,
 'lot': 0.0,
 'now': 0.0,
 'Learning': 0.07142857142857142,
 'campus': 0.0,
 'library': 0.0,
 'Our': 0.0,
 'and': 0.07142857142857142,
 'about': 0.07142857142857142,
 'in': 0.07142857142857142,
 'masters': 0.07142857142857142,
 'am': 0.07142857142857142,
 'Intelligence.': 0.07142857142857142,
 'I': 0.14285714285714285,
 'learning.': 0.0,
 'Machine': 0.07142857142857142,
 'reading': 0.07142857142857142,
 'doing': 0.07142857142857142,
 'enjoy': 0.07142857142857142,
 'Covid': 0.0,
 'stuck': 0.0,
 'lockdown.': 0.0,
 'lots': 0.0,
 'books': 0.0,
 'home': 0.0,
 'because': 0.0,
 'university': 0.0,
 'Artificial': 0.07142857142857142}

In [15]:
tf_2 = TF(word_dictionary_2,float(len(sentence_2)))
tf_2

{'my': 0.1111111111111111,
 'of': 0.05555555555555555,
 'has': 0.0,
 'a': 0.05555555555555555,
 'on': 0.0,
 'machine': 0.0,
 'but': 0.05555555555555555,
 'lot': 0.05555555555555555,
 'now': 0.05555555555555555,
 'Learning': 0.0,
 'campus': 0.05555555555555555,
 'library': 0.0,
 'Our': 0.0,
 'and': 0.0,
 'about': 0.0,
 'in': 0.1111111111111111,
 'masters': 0.0,
 'am': 0.0,
 'Intelligence.': 0.0,
 'I': 0.05555555555555555,
 'learning.': 0.0,
 'Machine': 0.0,
 'reading': 0.0,
 'doing': 0.0,
 'enjoy': 0.05555555555555555,
 'Covid': 0.05555555555555555,
 'stuck': 0.05555555555555555,
 'lockdown.': 0.05555555555555555,
 'lots': 0.0,
 'books': 0.0,
 'home': 0.05555555555555555,
 'because': 0.05555555555555555,
 'university': 0.05555555555555555,
 'Artificial': 0.0}

In [16]:
tf_3 = TF(word_dictionary_3,float(len(sentence_3)))
tf_3

{'my': 0.0,
 'of': 0.1,
 'has': 0.1,
 'a': 0.0,
 'on': 0.1,
 'machine': 0.1,
 'but': 0.0,
 'lot': 0.0,
 'now': 0.0,
 'Learning': 0.0,
 'campus': 0.0,
 'library': 0.1,
 'Our': 0.1,
 'and': 0.0,
 'about': 0.0,
 'in': 0.0,
 'masters': 0.0,
 'am': 0.0,
 'Intelligence.': 0.0,
 'I': 0.0,
 'learning.': 0.1,
 'Machine': 0.0,
 'reading': 0.0,
 'doing': 0.0,
 'enjoy': 0.0,
 'Covid': 0.0,
 'stuck': 0.0,
 'lockdown.': 0.0,
 'lots': 0.1,
 'books': 0.1,
 'home': 0.0,
 'because': 0.0,
 'university': 0.1,
 'Artificial': 0.0}

In [17]:
tf_frame = pd.DataFrame([tf_1,tf_2,tf_3])
tf_frame

,my,of,has,a,on,machine,but,lot,now,Learning,...,enjoy,Covid,stuck,lockdown.,lots,books,home,because,university,Artificial
0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.071429,...,0.071429,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.071429
1,0.111111,0.055556,0.0,0.055556,0.0,0.0,0.055556,0.055556,0.055556,0.000000,...,0.055556,0.055556,0.055556,0.055556,0.0,0.0,0.055556,0.055556,0.055556,0.000000
2,0.000000,0.100000,0.1,0.000000,0.1,0.1,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.1,0.1,0.000000,0.000000,0.100000,0.000000

In [18]:
tf_frame.T

                      0         1    2
my             0.000000  0.111111  0.0
of             0.000000  0.055556  0.1
has            0.000000  0.000000  0.1
a              0.000000  0.055556  0.0
on             0.000000  0.000000  0.1
machine        0.000000  0.000000  0.1
but            0.000000  0.055556  0.0
lot            0.000000  0.055556  0.0
now            0.000000  0.055556  0.0
Learning       0.071429  0.000000  0.0
campus         0.000000  0.055556  0.0
library        0.000000  0.000000  0.1
Our            0.000000  0.000000  0.1
and            0.071429  0.000000  0.0
about          0.071429  0.000000  0.0
in             0.071429  0.111111  0.0
masters        0.071429  0.000000  0.0
am             0.071429  0.000000  0.0
Intelligence.  0.071429  0.000000  0.0
I              0.142857  0.055556  0.0
learning.      0.000000  0.000000  0.1
Machine        0.071429  0.000000  0.0
reading        0.071429  0.000000  0.0
doing          0.071429  0.000000  0.0
enjoy          0.071429  0.055556  0.0
Covid          0.000000  0.055556  0.0
stuck          0.000000  0.055556  0.0
lockdown.      0.000000  0.055556  0.0
lots           0.000000  0.000000  0.1
books          0.000000  0.000000  0.1
home           0.000000  0.055556  0.0
because        0.000000  0.055556  0.0
university     0.000000  0.055556  0.1
Artificial     0.071429  0.000000  0.0

In [19]:
def idf(docs):
    idf_dict = {}
    idf_dict = word_dict()
    #length = len(docs)
    
    for doc in docs:
        for word, val in doc.items():
            if val > 0:
                idf_dict[word] += 1
    #for word , val in idf_dict.items():
    #    idf_dict[word] = math.log10(length / float(val))
    return idf_dict

In [20]:
def rg(docs):
    idf_dict = {}
    idf_dict = word_dict()
    length = len(docs)
    
    for doc in docs:
        for word, val in doc.items():
            if val > 0:
                idf_dict[word] += 1
    return idf_dict

In [21]:
def final_idf(documents):
    length = len(documents)
    idf_dict = {}
    idf_dict = word_dict()
    
    for doc in documents:
        count(idf_dict,doc)
    idf_dict = i_df(idf_dict, length)
    return idf_dict

In [22]:
def i_df(idf_dict,length):
    for word , val in idf_dict.items():
        idf_dict[word] = math.log10(length / float(val))
    return idf_dict

In [23]:
idf_dict = final_idf([sentence_1, sentence_2, sentence_3 ])
idf_dict

{'my': 0.17609125905568124,
 'of': 0.17609125905568124,
 'has': 0.47712125471966244,
 'a': 0.47712125471966244,
 'on': 0.47712125471966244,
 'machine': 0.47712125471966244,
 'but': 0.47712125471966244,
 'lot': 0.47712125471966244,
 'now': 0.47712125471966244,
 'Learning': 0.47712125471966244,
 'campus': 0.47712125471966244,
 'library': 0.47712125471966244,
 'Our': 0.47712125471966244,
 'and': 0.47712125471966244,
 'about': 0.47712125471966244,
 'in': 0.0,
 'masters': 0.47712125471966244,
 'am': 0.47712125471966244,
 'Intelligence.': 0.47712125471966244,
 'I': 0.0,
 'learning.': 0.47712125471966244,
 'Machine': 0.47712125471966244,
 'reading': 0.47712125471966244,
 'doing': 0.47712125471966244,
 'enjoy': 0.17609125905568124,
 'Covid': 0.47712125471966244,
 'stuck': 0.47712125471966244,
 'lockdown.': 0.47712125471966244,
 'lots': 0.47712125471966244,
 'books': 0.47712125471966244,
 'home': 0.47712125471966244,
 'because': 0.47712125471966244,
 'university': 0.17609125905568124,
 'Artificial': 0.47712125471966244}

In [24]:
def tf_idf(tf,idf_dict):
    tfidf = {}
    for word, val in tf.items():
        tfidf[word] = val*idf_dict[word]
    return tfidf

In [25]:
tfidf_1 = tf_idf(tf_1, idf_dict)
tfidf_1

{'my': 0.0,
 'of': 0.0,
 'has': 0.0,
 'a': 0.0,
 'on': 0.0,
 'machine': 0.0,
 'but': 0.0,
 'lot': 0.0,
 'now': 0.0,
 'Learning': 0.03408008962283303,
 'campus': 0.0,
 'library': 0.0,
 'Our': 0.0,
 'and': 0.03408008962283303,
 'about': 0.03408008962283303,
 'in': 0.0,
 'masters': 0.03408008962283303,
 'am': 0.03408008962283303,
 'Intelligence.': 0.03408008962283303,
 'I': 0.0,
 'learning.': 0.0,
 'Machine': 0.03408008962283303,
 'reading': 0.03408008962283303,
 'doing': 0.03408008962283303,
 'enjoy': 0.012577947075405802,
 'Covid': 0.0,
 'stuck': 0.0,
 'lockdown.': 0.0,
 'lots': 0.0,
 'books': 0.0,
 'home': 0.0,
 'because': 0.0,
 'university': 0.0,
 'Artificial': 0.03408008962283303}

In [26]:
tfidf_2 = tf_idf(tf_2, idf_dict)
tfidf_2

{'my': 0.01956569545063125,
 'of': 0.009782847725315624,
 'has': 0.0,
 'a': 0.026506736373314577,
 'on': 0.0,
 'machine': 0.0,
 'but': 0.026506736373314577,
 'lot': 0.026506736373314577,
 'now': 0.026506736373314577,
 'Learning': 0.0,
 'campus': 0.026506736373314577,
 'library': 0.0,
 'Our': 0.0,
 'and': 0.0,
 'about': 0.0,
 'in': 0.0,
 'masters': 0.0,
 'am': 0.0,
 'Intelligence.': 0.0,
 'I': 0.0,
 'learning.': 0.0,
 'Machine': 0.0,
 'reading': 0.0,
 'doing': 0.0,
 'enjoy': 0.009782847725315624,
 'Covid': 0.026506736373314577,
 'stuck': 0.026506736373314577,
 'lockdown.': 0.026506736373314577,
 'lots': 0.0,
 'books': 0.0,
 'home': 0.026506736373314577,
 'because': 0.026506736373314577,
 'university': 0.009782847725315624,
 'Artificial': 0.0}

In [27]:
tfidf_3 = tf_idf(tf_3, idf_dict)
tfidf_3

{'my': 0.0,
 'of': 0.017609125905568124,
 'has': 0.047712125471966245,
 'a': 0.0,
 'on': 0.047712125471966245,
 'machine': 0.047712125471966245,
 'but': 0.0,
 'lot': 0.0,
 'now': 0.0,
 'Learning': 0.0,
 'campus': 0.0,
 'library': 0.047712125471966245,
 'Our': 0.047712125471966245,
 'and': 0.0,
 'about': 0.0,
 'in': 0.0,
 'masters': 0.0,
 'am': 0.0,
 'Intelligence.': 0.0,
 'I': 0.0,
 'learning.': 0.047712125471966245,
 'Machine': 0.0,
 'reading': 0.0,
 'doing': 0.0,
 'enjoy': 0.0,
 'Covid': 0.0,
 'stuck': 0.0,
 'lockdown.': 0.0,
 'lots': 0.047712125471966245,
 'books': 0.047712125471966245,
 'home': 0.0,
 'because': 0.0,
 'university': 0.017609125905568124,
 'Artificial': 0.0}

In [28]:
score = pd.DataFrame([tfidf_1,tfidf_2,tfidf_3])
score.T

                      0         1         2
my             0.000000  0.019566  0.000000
of             0.000000  0.009783  0.017609
has            0.000000  0.000000  0.047712
a              0.000000  0.026507  0.000000
on             0.000000  0.000000  0.047712
machine        0.000000  0.000000  0.047712
but            0.000000  0.026507  0.000000
lot            0.000000  0.026507  0.000000
now            0.000000  0.026507  0.000000
Learning       0.034080  0.000000  0.000000
campus         0.000000  0.026507  0.000000
library        0.000000  0.000000  0.047712
Our            0.000000  0.000000  0.047712
and            0.034080  0.000000  0.000000
about          0.034080  0.000000  0.000000
in             0.000000  0.000000  0.000000
masters        0.034080  0.000000  0.000000
am             0.034080  0.000000  0.000000
Intelligence.  0.034080  0.000000  0.000000
I              0.000000  0.000000  0.000000
learning.      0.000000  0.000000  0.047712
Machine        0.034080  0.000000  0.000000
reading        0.034080  0.000000  0.000000
doing          0.034080  0.000000  0.000000
enjoy          0.012578  0.009783  0.000000
Covid          0.000000  0.026507  0.000000
stuck          0.000000  0.026507  0.000000
lockdown.      0.000000  0.026507  0.000000
lots           0.000000  0.000000  0.047712
books          0.000000  0.000000  0.047712
home           0.000000  0.026507  0.000000
because        0.000000  0.026507  0.000000
university     0.000000  0.009783  0.017609
Artificial     0.034080  0.000000  0.000000